### ISSUE TITLE
how to implement action in html.form

### ISSUE THREAD

**Issue by joesandiroz2** [volfpeter/htmy#8]
i see you docs . no guide about html.form . action

in html like this 

```
<form method="post" action="/post">
</form>
```

how to implement in you frameworks

  html.form(
            html.input_(type="text", name="item", placeholder="Add new item", required=True),
            html.input_(type="submit", value="Add"),
        ),

thx

**Comment by volfpeter** [comment]
Hi,

As with almost all tags, `html.form` can have both children (positional arguments) and properties (keyword arguments). So you can add form action and method like this:

```python
from htmy import form

html.form(
    html.input_(type="text", name="item", placeholder="Add new item", required=True),
    html.input_(type="submit", value="Add"),
    action="/item",
    method="post",
)
```

It would be nice to have IDE auto-completion for property names, but unfortunately Python's typing utilities don't really allow that in a flexible-enough way just yet.

**Comment by volfpeter** [comment]
As described in the docs, `htmy` is a rendering library, it (intentionally) does not have built-in client-server state synchronization like [reflex](https://reflex.dev/) or [nicegui](https://nicegui.io/). This means you can not write your event handlers in Python. Actually I strongly recommend using this library with [htmx](https://htmx.org/) and [alpinejs](https://alpinejs.dev/) for example, so you don't need to write much JavaScript, event handlers, and the like.

I'm not sure about your `C.Text(Visible=false, text="tess")` example. `htmy` does not have a built-in text component, there's also no `Visible` property. `htmy` gives you all the elements you have available in HTML. You can use those to build your own higher order components.

Regarding styling, there's a fairly detailed [example application](https://volfpeter.github.io/htmy/examples/fastapi-htmx-tailwind-daisyui/) in the docs that uses FastAPI, TailwindCSS, DaisyUI and HTMX for styling and interactivity. Please explore that example. Also, on top of CSS classnames, you can of course set the `style` attribute on HTML elements, they'll work as you'd expect in HTML.
